//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTasks.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public System.DateTime Date { get; set; }
        public string Lesson1 { get; set; }
        public int Group { get; set; }
        public int Subject { get; set; }
        public int Teacher { get; set; }
    
        public virtual Group Group1 { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
