//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTasks.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int Option1 { get; set; }
        public int Question { get; set; }
        public int Theme { get; set; }
    
        public virtual OptionText OptionText { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual Theme Theme1 { get; set; }
    }
}
